version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 16
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build

artifacts:
  files:
    - 'dist/**/*'
    - 'package.json'
    - 'node_modules/**/*'